apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Install a "kustomized-helm" plugin that renders a Helm chart, then uses Kustomize to render the final yaml
  # that will be used by ArgoCD to perform the installation. See: https://bit.ly/3vzGbpL
  #
  # The Helm template is rendered with following variables:
  # 
  # -) ARGOCD_APP_NAME: used for the Helm release name
  # -) ARGOCD_APP_NAMESPACE: used for the Helm release target namespace
  #
  # A calling Application can use following variables to alter behavior of plugin
  #
  # -) INCLUDE_CRDS: if true, renders CRDs along with Helm chart templates (default: false)
  configManagementPlugins: |
    - name: kustomized-helm
      init:
        command: ["/bin/sh", "-c"]
        args: ["helm dependency build"]
      generate:
        command: [sh, -c]
        args: ["helm template --release-name $ARGOCD_APP_NAME --namespace $ARGOCD_APP_NAMESPACE --include-crds=${INCLUDE_CRDS:-false} . > all.yaml && kustomize build"]